### ISSUE TITLE
#1 Fix Vue Recipe card component 

### ISSUE THREAD

**Issue by KristianWEB** [KristianWEB/recipe-manager#3]
**Is your feature request related to a problem? Please describe.**

The Vue Recipe card component is not mobile-friendly. Utilize tailwind to fix responsive issues so the cards can scale on any resolution.
  
We need to make ingredient lists shorter so the Recipe Vue components can be at the same width without wasting too much occupation. If the list which contains all the ingredients is `really long` replace some of them with a placeholder `[...]`.

You can work on this feature using a branch called `feature/fix-recipe-card`.

**Comment by PreslavDEV** [comment]
Fixed vue recipe card component. Sent pull request.
