### ISSUE TITLE
#2 Fix Login/Register Forms

### ISSUE THREAD

**Issue by KristianWEB** [KristianWEB/recipe-manager#4]
**Is your feature request related to a problem? Please describe.**

**1.** Style the Login and the Register Form so they have a normal look.

**2.**  The Login and Register form Vue components are not mobile-friendly. Utilize tailwind to fix responsive issues so the forms can scale on any resolution.

**3.** The user needs a feedback from the app when logging in successfully. After the ajax request is resolved, put a success message below the form. 

**4.** When we click on Login Form ( clicking any link that requires authentication ) and then click on register, and then if we want to come back there is a login link on the register form but it shows below the register form. Refactor the code so the login form shows again on top of the register form.

You can work on this feature using a branch called `feature/fix-login-register-forms`.

**Comment by PreslavDEV** [comment]
Fixed login and register forms. Sent pull request.
